Associative list problems
fmi-lab/fp-elective-2017 pull request #10
Opened 2017-11-19 19:40 UTC by antonpetkoff

2017-11-19 22:53 UTC, dimitaruzunov requested changes

2017-11-19 22:53 UTC, dimitaruzunov commented on exercises/07/README.md
> +   - `'((1 . 2) (1 . 3) (15 . 2))` - в зависимост проблема, който решавате, можете да повтаряте ключове.
`в зависимост проблема, който решавате, можете да повтаряте` -> `в зависимост от проблема, който решаваме, можем да повтаряме` (да сме консистентни с рода и числото - първо лице, множествено число, както е в долния пример 😂).

2017-11-19 22:53 UTC, dimitaruzunov commented on exercises/07/README.md
> +възстановява списъка, който е закодиран чрез `run-length-encode` от предната задача
`закодиран` -> `кодиран`

2017-11-19 22:53 UTC, dimitaruzunov commented on exercises/07/README.md
> +връща асоциативен списък, в който ключовете са стойностите на функцията `f` след прилагането й върху елементи от списъка `l`, а
`й` -> `ѝ`

2017-11-20 06:39 UTC, antonpetkoff commented on exercises/07/README.md
> +връща асоциативен списък, в който ключовете са стойностите на функцията `f` след прилагането й върху елементи от списъка `l`, а
Нямам такъв символ на клавиатурата :D

2017-11-20 12:31 UTC, dimitaruzunov approved these changes

2017-11-20 12:31 UTC, merged